/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.admin;

import dao.Account;
import dao.Table;
import dao.Reservation;
import dao.ReservationDetail;
import java.sql.Date;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.AccountService;
import services.TableService;
import services.ReservationService;

public class ReservationsManagement extends javax.swing.JFrame {

    /**
     * Creates new form UsersManagement
     */
    public ReservationsManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbReservation = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnGet = new javax.swing.JButton();
        btnComplete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ ĐẶT BÀN");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Quản lý đặt bàn");
        jLabel1.setToolTipText("");

        tbReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ID", "Họ tên", "Bàn số", "Thời gian", "Tình trạng", "Số điện thoại", "Số ghế", "Flag"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbReservation.getTableHeader().setResizingAllowed(false);
        tbReservation.getTableHeader().setReorderingAllowed(false);
        tbReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbReservationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbReservation);

        jButton1.setText("Đóng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnApprove.setText("Duyệt");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setText("Hủy");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnGet.setText("Xem");
        btnGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetActionPerformed(evt);
            }
        });

        btnComplete.setText("Xóa");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(btnGet, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnApprove)
                        .addGap(51, 51, 51)
                        .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnComplete)
                        .addGap(44, 44, 44)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jLabel1)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnApprove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnComplete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            tbReservation.removeColumn(tbReservation.getColumnModel().getColumn(8));
        } catch (Exception e) {
        }

        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");

        List<Reservation> reservations = reservationService.getAllReservations();

        DefaultTableModel model = (DefaultTableModel) tbReservation.getModel();
        model.setRowCount(0);

        for (int i = 0; i < reservations.size(); i++) {
            Reservation reservation = reservations.get(i);
            Table table = tableService.getTableId(reservation.getTableId());
            Account account = accountService.getAccountByTableId(table.getTableId());
            model.addRow(new Object[]{i + 1, reservation.getReservationId(), account.getFullName(), table.getNumber(), simpleDateFormat.format(reservation.getReservationTime()), reservation.getStatus(), account.getPhone(), table.getSeats(), reservation.getFlag()});
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AdminScreenMain adminScreenMain = new AdminScreenMain();
        adminScreenMain.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbReservationMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) tbReservation.getModel();
        Vector<Object> courseVector = (Vector<Object>) tableModel.getDataVector().elementAt(tbReservation.getSelectedRow());
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        reservationDetail.setReservationId(Integer.valueOf(courseVector.get(1).toString()));
        reservationDetail.setFullName(courseVector.get(2).toString()); 
        reservationDetail.setNumber(Integer.valueOf(courseVector.get(3).toString()));
        reservationDetail.setReservationTime(java.sql.Date.valueOf(courseVector.get(4).toString()));
        reservationDetail.setStatus(courseVector.get(5).toString());
        reservationDetail.setPhone(courseVector.get(6).toString());
        reservationDetail.setSeats(Integer.valueOf(courseVector.get(7).toString()));
        reservationDetail.setFlag(Integer.valueOf(courseVector.get(8).toString()));
    }//GEN-LAST:event_tbReservationMouseClicked

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:

        if (reservationDetail.getReservationId() != null) {
            reservationDetail.setStatus("Đã bị từ chối");
            reservationDetail.setFlag(-1);
            reservationService.Update(reservationDetail);
            int responseConfirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn hủy không?", "Hủy đặt bàn", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (responseConfirm == JOptionPane.YES_OPTION) {
                if (!reservationService.Update(reservationDetail)) {
                    JOptionPane.showConfirmDialog(null, "Hủy thất bại", "Hủy đặt bàn", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
                    return;
                }

                JOptionPane.showConfirmDialog(null, "Hủy thành công", "Hủy đặt bàn", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                formWindowOpened(null);
            }
        }
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // TODO add your handling code here:
        if (reservationDetail.getReservationId() != null) {
            if (!reservationService.Delete(reservationDetail.getReservationId())) {
                JOptionPane.showConfirmDialog(null, "Xóa thất bại", "Xóa đặt bàn", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showConfirmDialog(null, "Xóa thành công", "Xóa đặt bàn", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
            formWindowOpened(null);
        }
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void btnGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetActionPerformed
        // TODO add your handling code here:
        if (reservationDetail.getReservationId() != null) {
            JOptionPane.showConfirmDialog(null, reservationDetail.toString(), "Thông tin chi tiết", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGetActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        if (reservationDetail.getReservationId() != null) {
            reservationDetail.setStatus("Đặt thành công");
            reservationDetail.setFlag(1);
            reservationService.Update(reservationDetail);
            if (!reservationService.Update(reservationDetail)) {
                JOptionPane.showConfirmDialog(null, "Duyệt thất bại", "Duyệt đặt bàn", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
                return;
            }

            JOptionPane.showConfirmDialog(null, "Duyệt thành công", "Duyệt đặt bàn", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
            formWindowOpened(null);
        }
    }//GEN-LAST:event_btnApproveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationsManagement.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationsManagement.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationsManagement.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationsManagement.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationsManagement().setVisible(true);
            }
        });
    }

    private ReservationService reservationService = new ReservationService();
    private AccountService accountService = new AccountService();
    private TableService tableService = new TableService();
    private ReservationDetail reservationDetail = new ReservationDetail();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnGet;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbReservation;
    // End of variables declaration//GEN-END:variables
}
