/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.member;

import dao.Reservation;
import dao.ReservationDetail;
import dao.Table;
import dao.UserLogin;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.ReservationService;
import services.TableService;

public class ReservationManagement extends javax.swing.JFrame {

    /**
     * Creates new form UsersManagement
     */
    public ReservationManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnReverve = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbReservation = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ BÀN");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Lịch sử đặt bàn");

        jButton1.setText("Đóng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnReverve.setText("Đặt bàn");
        btnReverve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReverveActionPerformed(evt);
            }
        });

        btnDelete.setText("Hủy đặt");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tbReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ID", "Bàn số", "Thời gian", "Tình trạng", "Số ghế", "Flag"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbReservation.getTableHeader().setResizingAllowed(false);
        tbReservation.getTableHeader().setReorderingAllowed(false);
        tbReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbReservationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbReservation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(btnReverve, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReverve)
                    .addComponent(btnDelete)
                    .addComponent(jButton1))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            tbReservation.removeColumn(tbReservation.getColumnModel().getColumn(6));
        } catch (Exception e) {
        }

        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");

        List<Reservation> reservations = reservationService.getAllReservationsByAccountId(UserLogin.getAccountId());

        DefaultTableModel model = (DefaultTableModel) tbReservation.getModel();
        model.setRowCount(0);

        for (int i = 0; i < reservations.size(); i++) {
            Reservation reservation = reservations.get(i);
            Table table = tableService.getTableId(reservation.getTableId());
            model.addRow(new Object[]{i + 1, reservation.getReservationId(), table.getNumber(), simpleDateFormat.format(reservation.getReservationTime()), reservation.getStatus(), table.getSeats(), reservation.getFlag()});
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MemberScreenMain memberScreenMain = new MemberScreenMain();
        memberScreenMain.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnReverveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReverveActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AddReservationFrame addReservationFrame = new AddReservationFrame();
        addReservationFrame.setVisible(true);
    }//GEN-LAST:event_btnReverveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (reservationDetail.getReservationId()!= null) {
            if (reservationService.Delete(reservationDetail.getReservationId())) {
                JOptionPane.showConfirmDialog(null, "Xóa thành công", "Xóa đặt bàn", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                formWindowOpened(null);
                return;
            }
        }
        JOptionPane.showConfirmDialog(null, "Xóa thất bại", "Xóa đặt bàn", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tbReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbReservationMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) tbReservation.getModel();
        Vector<Object> courseVector = (Vector<Object>) tableModel.getDataVector().elementAt(tbReservation.getSelectedRow());

        reservationDetail.setReservationId(Integer.valueOf(courseVector.get(1).toString()));
        reservationDetail.setNumber(Integer.valueOf(courseVector.get(2).toString()));
        reservationDetail.setReservationTime(Date.valueOf(courseVector.get(3).toString()));
        reservationDetail.setStatus(courseVector.get(4).toString());
        reservationDetail.setSeats(Integer.valueOf(courseVector.get(5).toString()));
        reservationDetail.setFlag(Integer.valueOf(courseVector.get(6).toString()));
    }//GEN-LAST:event_tbReservationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationManagement().setVisible(true);
            }
        });
    }

    private ReservationService reservationService = new ReservationService();
    private TableService tableService = new TableService();
    private ReservationDetail reservationDetail = new ReservationDetail();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReverve;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbReservation;
    // End of variables declaration//GEN-END:variables
}
